# Generated by Django 5.2.4 on 2025-07-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("rating", models.FloatField()),
                ("rating_count", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("image", models.URLField()),
                ("badge", models.CharField(blank=True, max_length=50)),
                ("supplier", models.CharField(max_length=255)),
                ("supplier_image", models.URLField()),
                ("description", models.TextField()),
            ],
        ),
    ]
