# Generated by Django 5.2.4 on 2025-07-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50, unique=True)),
                ("customer", models.CharField(max_length=255)),
                ("item_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
                ("progress", models.IntegerField(default=0)),
            ],
        ),
    ]
