# Generated by Django 5.2.4 on 2025-07-26 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.vendorprofile",
            ),
        ),
    ]
