# Generated by Django 5.2.4 on 2025-07-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_order_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="progress",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="vendor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.vendorprofile",
            ),
            preserve_default=False,
        ),
    ]
