# Generated by Django 5.2.4 on 2025-07-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_order_created_at_alter_order_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplierprofile",
            options={},
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="certifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SharedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50)),
                ("item_name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                ("progress", models.IntegerField(default=1)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_orders",
                        to="accounts.supplierprofile",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_shared_orders",
                        to="accounts.vendorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_orders", models.PositiveIntegerField(default=0)),
                ("active_products", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("revenue_labels", models.JSONField(default=list)),
                ("revenue_data", models.JSONField(default=list)),
                ("category_labels", models.JSONField(default=list)),
                ("category_data", models.JSONField(default=list)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="accounts.supplierprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "custom_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_inventories",
                        to="accounts.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="accounts.supplierprofile",
                    ),
                ),
            ],
        ),
    ]
